<?php
/**
 * InsightsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\BolClient\GeneratedApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\BolClient\ApiException;
use Swagger\BolClient\Configuration;
use Swagger\BolClient\HeaderSelector;
use Swagger\BolClient\ObjectSerializer;

/**
 * InsightsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InsightsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getOfferInsights
     *
     * Get offer insights
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  string $period The time unit in which the offer insights are grouped. (required)
     * @param  int $number_of_periods The number of periods for which the offer insights are requested back in time. (required)
     * @param  string[] $name The name of the requested offer insight. (required)
     *
     * @throws \Swagger\BolClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\BolClient\Model\OfferInsights
     */
    public function getOfferInsights($offer_id, $period, $number_of_periods, $name)
    {
        list($response) = $this->getOfferInsightsWithHttpInfo($offer_id, $period, $number_of_periods, $name);
        return $response;
    }

    /**
     * Operation getOfferInsightsWithHttpInfo
     *
     * Get offer insights
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  string $period The time unit in which the offer insights are grouped. (required)
     * @param  int $number_of_periods The number of periods for which the offer insights are requested back in time. (required)
     * @param  string[] $name The name of the requested offer insight. (required)
     *
     * @throws \Swagger\BolClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\BolClient\Model\OfferInsights, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOfferInsightsWithHttpInfo($offer_id, $period, $number_of_periods, $name)
    {
        $returnType = '\Swagger\BolClient\Model\OfferInsights';
        $request = $this->getOfferInsightsRequest($offer_id, $period, $number_of_periods, $name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\BolClient\Model\OfferInsights',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\BolClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getOfferInsightsAsync
     *
     * Get offer insights
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  string $period The time unit in which the offer insights are grouped. (required)
     * @param  int $number_of_periods The number of periods for which the offer insights are requested back in time. (required)
     * @param  string[] $name The name of the requested offer insight. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOfferInsightsAsync($offer_id, $period, $number_of_periods, $name)
    {
        return $this->getOfferInsightsAsyncWithHttpInfo($offer_id, $period, $number_of_periods, $name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOfferInsightsAsyncWithHttpInfo
     *
     * Get offer insights
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  string $period The time unit in which the offer insights are grouped. (required)
     * @param  int $number_of_periods The number of periods for which the offer insights are requested back in time. (required)
     * @param  string[] $name The name of the requested offer insight. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOfferInsightsAsyncWithHttpInfo($offer_id, $period, $number_of_periods, $name)
    {
        $returnType = '\Swagger\BolClient\Model\OfferInsights';
        $request = $this->getOfferInsightsRequest($offer_id, $period, $number_of_periods, $name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOfferInsights'
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  string $period The time unit in which the offer insights are grouped. (required)
     * @param  int $number_of_periods The number of periods for which the offer insights are requested back in time. (required)
     * @param  string[] $name The name of the requested offer insight. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getOfferInsightsRequest($offer_id, $period, $number_of_periods, $name)
    {
        // verify the required parameter 'offer_id' is set
        if ($offer_id === null || (is_array($offer_id) && count($offer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $offer_id when calling getOfferInsights'
            );
        }
        // verify the required parameter 'period' is set
        if ($period === null || (is_array($period) && count($period) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $period when calling getOfferInsights'
            );
        }
        // verify the required parameter 'number_of_periods' is set
        if ($number_of_periods === null || (is_array($number_of_periods) && count($number_of_periods) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $number_of_periods when calling getOfferInsights'
            );
        }
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getOfferInsights'
            );
        }

        $resourcePath = '/retailer/insights/offer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($offer_id !== null) {
            $queryParams['offer-id'] = ObjectSerializer::toQueryValue($offer_id);
        }
        // query params
        if ($period !== null) {
            $queryParams['period'] = ObjectSerializer::toQueryValue($period);
        }
        // query params
        if ($number_of_periods !== null) {
            $queryParams['number-of-periods'] = ObjectSerializer::toQueryValue($number_of_periods);
        }
        // query params
        if (is_array($name)) {
            $queryParams['name'] = $name;
        } else
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.retailer.v4+json', 'application/vnd.retailer.v4+xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.retailer.v4+json', 'application/vnd.retailer.v4+xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPerformanceIndicator
     *
     * Get performance indicators
     *
     * @param  string[] $name The type of the performance indicator (required)
     * @param  string $year Year number in the ISO-8601 standard. (required)
     * @param  string $week Week number in the ISO-8601 standard. If you would like to get the relative scores from the current week, please provide the current week number here. Be advised that measurements can change heavily over the course of the week. (required)
     *
     * @throws \Swagger\BolClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\BolClient\Model\PerformanceIndicators
     */
    public function getPerformanceIndicator($name, $year, $week)
    {
        list($response) = $this->getPerformanceIndicatorWithHttpInfo($name, $year, $week);
        return $response;
    }

    /**
     * Operation getPerformanceIndicatorWithHttpInfo
     *
     * Get performance indicators
     *
     * @param  string[] $name The type of the performance indicator (required)
     * @param  string $year Year number in the ISO-8601 standard. (required)
     * @param  string $week Week number in the ISO-8601 standard. If you would like to get the relative scores from the current week, please provide the current week number here. Be advised that measurements can change heavily over the course of the week. (required)
     *
     * @throws \Swagger\BolClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\BolClient\Model\PerformanceIndicators, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPerformanceIndicatorWithHttpInfo($name, $year, $week)
    {
        $returnType = '\Swagger\BolClient\Model\PerformanceIndicators';
        $request = $this->getPerformanceIndicatorRequest($name, $year, $week);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\BolClient\Model\PerformanceIndicators',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPerformanceIndicatorAsync
     *
     * Get performance indicators
     *
     * @param  string[] $name The type of the performance indicator (required)
     * @param  string $year Year number in the ISO-8601 standard. (required)
     * @param  string $week Week number in the ISO-8601 standard. If you would like to get the relative scores from the current week, please provide the current week number here. Be advised that measurements can change heavily over the course of the week. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPerformanceIndicatorAsync($name, $year, $week)
    {
        return $this->getPerformanceIndicatorAsyncWithHttpInfo($name, $year, $week)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPerformanceIndicatorAsyncWithHttpInfo
     *
     * Get performance indicators
     *
     * @param  string[] $name The type of the performance indicator (required)
     * @param  string $year Year number in the ISO-8601 standard. (required)
     * @param  string $week Week number in the ISO-8601 standard. If you would like to get the relative scores from the current week, please provide the current week number here. Be advised that measurements can change heavily over the course of the week. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPerformanceIndicatorAsyncWithHttpInfo($name, $year, $week)
    {
        $returnType = '\Swagger\BolClient\Model\PerformanceIndicators';
        $request = $this->getPerformanceIndicatorRequest($name, $year, $week);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPerformanceIndicator'
     *
     * @param  string[] $name The type of the performance indicator (required)
     * @param  string $year Year number in the ISO-8601 standard. (required)
     * @param  string $week Week number in the ISO-8601 standard. If you would like to get the relative scores from the current week, please provide the current week number here. Be advised that measurements can change heavily over the course of the week. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getPerformanceIndicatorRequest($name, $year, $week)
    {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getPerformanceIndicator'
            );
        }
        // verify the required parameter 'year' is set
        if ($year === null || (is_array($year) && count($year) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $year when calling getPerformanceIndicator'
            );
        }
        // verify the required parameter 'week' is set
        if ($week === null || (is_array($week) && count($week) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $week when calling getPerformanceIndicator'
            );
        }

        $resourcePath = '/retailer/insights/performance/indicator';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($name)) {
            $queryParams['name'] = $name;
        } else
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name);
        }
        // query params
        if ($year !== null) {
            $queryParams['year'] = ObjectSerializer::toQueryValue($year);
        }
        // query params
        if ($week !== null) {
            $queryParams['week'] = ObjectSerializer::toQueryValue($week);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.retailer.v4+json', 'application/vnd.retailer.v4+xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.retailer.v4+json', 'application/vnd.retailer.v4+xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSalesForecast
     *
     * Get sales forecast
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  int $weeks_ahead The number of weeks into the future, starting from today. (required)
     *
     * @throws \Swagger\BolClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\BolClient\Model\SalesForecastResponse
     */
    public function getSalesForecast($offer_id, $weeks_ahead)
    {
        list($response) = $this->getSalesForecastWithHttpInfo($offer_id, $weeks_ahead);
        return $response;
    }

    /**
     * Operation getSalesForecastWithHttpInfo
     *
     * Get sales forecast
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  int $weeks_ahead The number of weeks into the future, starting from today. (required)
     *
     * @throws \Swagger\BolClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\BolClient\Model\SalesForecastResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSalesForecastWithHttpInfo($offer_id, $weeks_ahead)
    {
        $returnType = '\Swagger\BolClient\Model\SalesForecastResponse';
        $request = $this->getSalesForecastRequest($offer_id, $weeks_ahead);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\BolClient\Model\SalesForecastResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\BolClient\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSalesForecastAsync
     *
     * Get sales forecast
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  int $weeks_ahead The number of weeks into the future, starting from today. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSalesForecastAsync($offer_id, $weeks_ahead)
    {
        return $this->getSalesForecastAsyncWithHttpInfo($offer_id, $weeks_ahead)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSalesForecastAsyncWithHttpInfo
     *
     * Get sales forecast
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  int $weeks_ahead The number of weeks into the future, starting from today. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSalesForecastAsyncWithHttpInfo($offer_id, $weeks_ahead)
    {
        $returnType = '\Swagger\BolClient\Model\SalesForecastResponse';
        $request = $this->getSalesForecastRequest($offer_id, $weeks_ahead);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSalesForecast'
     *
     * @param  string $offer_id Unique identifier for an offer. (required)
     * @param  int $weeks_ahead The number of weeks into the future, starting from today. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSalesForecastRequest($offer_id, $weeks_ahead)
    {
        // verify the required parameter 'offer_id' is set
        if ($offer_id === null || (is_array($offer_id) && count($offer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $offer_id when calling getSalesForecast'
            );
        }
        // verify the required parameter 'weeks_ahead' is set
        if ($weeks_ahead === null || (is_array($weeks_ahead) && count($weeks_ahead) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $weeks_ahead when calling getSalesForecast'
            );
        }

        $resourcePath = '/retailer/insights/sales-forecast';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($offer_id !== null) {
            $queryParams['offer-id'] = ObjectSerializer::toQueryValue($offer_id);
        }
        // query params
        if ($weeks_ahead !== null) {
            $queryParams['weeks-ahead'] = ObjectSerializer::toQueryValue($weeks_ahead);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.retailer.v4+json', 'application/vnd.retailer.v4+xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.retailer.v4+json', 'application/vnd.retailer.v4+xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
