<?php
/**
 * ChangeTransportRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\BolClient\Model;

use \ArrayAccess;
use \Swagger\BolClient\ObjectSerializer;

/**
 * ChangeTransportRequest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChangeTransportRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ChangeTransportRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'transporter_code' => 'string',
        'track_and_trace' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'transporter_code' => null,
        'track_and_trace' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transporter_code' => 'transporterCode',
        'track_and_trace' => 'trackAndTrace'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transporter_code' => 'setTransporterCode',
        'track_and_trace' => 'setTrackAndTrace'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transporter_code' => 'getTransporterCode',
        'track_and_trace' => 'getTrackAndTrace'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TRANSPORTER_CODE_BRIEFPOST = 'BRIEFPOST';
    const TRANSPORTER_CODE_UPS = 'UPS';
    const TRANSPORTER_CODE_TNT = 'TNT';
    const TRANSPORTER_CODE_TNT_EXTRA = 'TNT-EXTRA';
    const TRANSPORTER_CODE_TNT_BRIEF = 'TNT_BRIEF';
    const TRANSPORTER_CODE_TNT_EXPRESS = 'TNT-EXPRESS';
    const TRANSPORTER_CODE_DYL = 'DYL';
    const TRANSPORTER_CODE_DPD_NL = 'DPD-NL';
    const TRANSPORTER_CODE_DPD_BE = 'DPD-BE';
    const TRANSPORTER_CODE_BPOST_BE = 'BPOST_BE';
    const TRANSPORTER_CODE_BPOST_BRIEF = 'BPOST_BRIEF';
    const TRANSPORTER_CODE_DHLFORYOU = 'DHLFORYOU';
    const TRANSPORTER_CODE_GLS = 'GLS';
    const TRANSPORTER_CODE_FEDEX_NL = 'FEDEX_NL';
    const TRANSPORTER_CODE_FEDEX_BE = 'FEDEX_BE';
    const TRANSPORTER_CODE_OTHER = 'OTHER';
    const TRANSPORTER_CODE_DHL = 'DHL';
    const TRANSPORTER_CODE_DHL_DE = 'DHL_DE';
    const TRANSPORTER_CODE_DHL_GLOBAL_MAIL = 'DHL-GLOBAL-MAIL';
    const TRANSPORTER_CODE_TSN = 'TSN';
    const TRANSPORTER_CODE_FIEGE = 'FIEGE';
    const TRANSPORTER_CODE_TRANSMISSION = 'TRANSMISSION';
    const TRANSPORTER_CODE_PARCEL_NL = 'PARCEL-NL';
    const TRANSPORTER_CODE_LOGOIX = 'LOGOIX';
    const TRANSPORTER_CODE_PACKS = 'PACKS';
    const TRANSPORTER_CODE_COURIER = 'COURIER';
    const TRANSPORTER_CODE_RJP = 'RJP';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTransporterCodeAllowableValues()
    {
        return [
            self::TRANSPORTER_CODE_BRIEFPOST,
            self::TRANSPORTER_CODE_UPS,
            self::TRANSPORTER_CODE_TNT,
            self::TRANSPORTER_CODE_TNT_EXTRA,
            self::TRANSPORTER_CODE_TNT_BRIEF,
            self::TRANSPORTER_CODE_TNT_EXPRESS,
            self::TRANSPORTER_CODE_DYL,
            self::TRANSPORTER_CODE_DPD_NL,
            self::TRANSPORTER_CODE_DPD_BE,
            self::TRANSPORTER_CODE_BPOST_BE,
            self::TRANSPORTER_CODE_BPOST_BRIEF,
            self::TRANSPORTER_CODE_DHLFORYOU,
            self::TRANSPORTER_CODE_GLS,
            self::TRANSPORTER_CODE_FEDEX_NL,
            self::TRANSPORTER_CODE_FEDEX_BE,
            self::TRANSPORTER_CODE_OTHER,
            self::TRANSPORTER_CODE_DHL,
            self::TRANSPORTER_CODE_DHL_DE,
            self::TRANSPORTER_CODE_DHL_GLOBAL_MAIL,
            self::TRANSPORTER_CODE_TSN,
            self::TRANSPORTER_CODE_FIEGE,
            self::TRANSPORTER_CODE_TRANSMISSION,
            self::TRANSPORTER_CODE_PARCEL_NL,
            self::TRANSPORTER_CODE_LOGOIX,
            self::TRANSPORTER_CODE_PACKS,
            self::TRANSPORTER_CODE_COURIER,
            self::TRANSPORTER_CODE_RJP,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transporter_code'] = isset($data['transporter_code']) ? $data['transporter_code'] : null;
        $this->container['track_and_trace'] = isset($data['track_and_trace']) ? $data['track_and_trace'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTransporterCodeAllowableValues();
        if (!is_null($this->container['transporter_code']) && !in_array($this->container['transporter_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'transporter_code', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transporter_code
     *
     * @return string
     */
    public function getTransporterCode()
    {
        return $this->container['transporter_code'];
    }

    /**
     * Sets transporter_code
     *
     * @param string $transporter_code transporter_code
     *
     * @return $this
     */
    public function setTransporterCode($transporter_code)
    {
        $allowedValues = $this->getTransporterCodeAllowableValues();
        if (!is_null($transporter_code) && !in_array($transporter_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'transporter_code', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['transporter_code'] = $transporter_code;

        return $this;
    }

    /**
     * Gets track_and_trace
     *
     * @return string
     */
    public function getTrackAndTrace()
    {
        return $this->container['track_and_trace'];
    }

    /**
     * Sets track_and_trace
     *
     * @param string $track_and_trace The track and trace code that is associated with this transport.
     *
     * @return $this
     */
    public function setTrackAndTrace($track_and_trace)
    {
        $this->container['track_and_trace'] = $track_and_trace;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


