<?php
/**
 * ModelReturnTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\BolClient;

/**
 * ModelReturnTest Class Doc Comment
 *
 * @category    Class
 * @description ModelReturn
 * @package     Swagger\BolClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelReturnTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelReturn"
     */
    public function testModelReturn()
    {
    }

    /**
     * Test attribute "return_id"
     */
    public function testPropertyReturnId()
    {
    }

    /**
     * Test attribute "registration_date_time"
     */
    public function testPropertyRegistrationDateTime()
    {
    }

    /**
     * Test attribute "fulfilment_method"
     */
    public function testPropertyFulfilmentMethod()
    {
    }

    /**
     * Test attribute "return_items"
     */
    public function testPropertyReturnItems()
    {
    }
}
