<?php
/**
 * ReducedInboundTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\BolClient;

/**
 * ReducedInboundTest Class Doc Comment
 *
 * @category    Class
 * @description ReducedInbound
 * @package     Swagger\BolClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReducedInboundTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReducedInbound"
     */
    public function testReducedInbound()
    {
    }

    /**
     * Test attribute "inbound_id"
     */
    public function testPropertyInboundId()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "creation_date_time"
     */
    public function testPropertyCreationDateTime()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "labelling_service"
     */
    public function testPropertyLabellingService()
    {
    }

    /**
     * Test attribute "announced_bsk_us"
     */
    public function testPropertyAnnouncedBskUs()
    {
    }

    /**
     * Test attribute "announced_quantity"
     */
    public function testPropertyAnnouncedQuantity()
    {
    }

    /**
     * Test attribute "received_bsk_us"
     */
    public function testPropertyReceivedBskUs()
    {
    }

    /**
     * Test attribute "received_quantity"
     */
    public function testPropertyReceivedQuantity()
    {
    }

    /**
     * Test attribute "time_slot"
     */
    public function testPropertyTimeSlot()
    {
    }

    /**
     * Test attribute "inbound_transporter"
     */
    public function testPropertyInboundTransporter()
    {
    }
}
