<?php
/**
 * ReturnItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\BolClient;

/**
 * ReturnItemTest Class Doc Comment
 *
 * @category    Class
 * @description ReturnItem
 * @package     Swagger\BolClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReturnItem"
     */
    public function testReturnItem()
    {
    }

    /**
     * Test attribute "rma_id"
     */
    public function testPropertyRmaId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "expected_quantity"
     */
    public function testPropertyExpectedQuantity()
    {
    }

    /**
     * Test attribute "return_reason"
     */
    public function testPropertyReturnReason()
    {
    }

    /**
     * Test attribute "return_reason_comments"
     */
    public function testPropertyReturnReasonComments()
    {
    }

    /**
     * Test attribute "track_and_trace"
     */
    public function testPropertyTrackAndTrace()
    {
    }

    /**
     * Test attribute "transporter_name"
     */
    public function testPropertyTransporterName()
    {
    }

    /**
     * Test attribute "handled"
     */
    public function testPropertyHandled()
    {
    }

    /**
     * Test attribute "processing_results"
     */
    public function testPropertyProcessingResults()
    {
    }

    /**
     * Test attribute "customer_details"
     */
    public function testPropertyCustomerDetails()
    {
    }
}
