<?php
/**
 * ShipmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\BolClient;

/**
 * ShipmentTest Class Doc Comment
 *
 * @category    Class
 * @description Shipment
 * @package     Swagger\BolClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Shipment"
     */
    public function testShipment()
    {
    }

    /**
     * Test attribute "shipment_id"
     */
    public function testPropertyShipmentId()
    {
    }

    /**
     * Test attribute "shipment_date_time"
     */
    public function testPropertyShipmentDateTime()
    {
    }

    /**
     * Test attribute "shipment_reference"
     */
    public function testPropertyShipmentReference()
    {
    }

    /**
     * Test attribute "pick_up_point"
     */
    public function testPropertyPickUpPoint()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "shipment_details"
     */
    public function testPropertyShipmentDetails()
    {
    }

    /**
     * Test attribute "billing_details"
     */
    public function testPropertyBillingDetails()
    {
    }

    /**
     * Test attribute "shipping_label_id"
     */
    public function testPropertyShippingLabelId()
    {
    }

    /**
     * Test attribute "shipment_items"
     */
    public function testPropertyShipmentItems()
    {
    }

    /**
     * Test attribute "transport"
     */
    public function testPropertyTransport()
    {
    }
}
