<?php
/**
 * ShipmentTransportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\BolClient;

/**
 * ShipmentTransportTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentTransport
 * @package     Swagger\BolClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentTransportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShipmentTransport"
     */
    public function testShipmentTransport()
    {
    }

    /**
     * Test attribute "transport_id"
     */
    public function testPropertyTransportId()
    {
    }

    /**
     * Test attribute "transporter_code"
     */
    public function testPropertyTransporterCode()
    {
    }

    /**
     * Test attribute "track_and_trace"
     */
    public function testPropertyTrackAndTrace()
    {
    }
}
