<?php
/**
 * InboundsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\BolClient;

use \Swagger\BolClient\Configuration;
use \Swagger\BolClient\ApiException;
use \Swagger\BolClient\ObjectSerializer;

/**
 * InboundsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboundsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getDeliveryWindows
     *
     * Get delivery windows for new inbound shipments.
     *
     */
    public function testGetDeliveryWindows()
    {
    }

    /**
     * Test case for getInbound
     *
     * Get inbound by inbound id.
     *
     */
    public function testGetInbound()
    {
    }

    /**
     * Test case for getInboundShippingLabel
     *
     * Get inbound shipping label by inbound id.
     *
     */
    public function testGetInboundShippingLabel()
    {
    }

    /**
     * Test case for getInboundTransporters
     *
     * Get inbound transporters list.
     *
     */
    public function testGetInboundTransporters()
    {
    }

    /**
     * Test case for getInbounds
     *
     * Get inbound shipment list.
     *
     */
    public function testGetInbounds()
    {
    }

    /**
     * Test case for getPackingList
     *
     * Get packing list by inbound id.
     *
     */
    public function testGetPackingList()
    {
    }

    /**
     * Test case for getProductLabels
     *
     * Get inbound product labels by EAN.
     *
     */
    public function testGetProductLabels()
    {
    }

    /**
     * Test case for postInbound
     *
     * Post inbound shipment.
     *
     */
    public function testPostInbound()
    {
    }
}
