<?php
/**
 * ReturnsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\BolClient;

use \Swagger\BolClient\Configuration;
use \Swagger\BolClient\ApiException;
use \Swagger\BolClient\ObjectSerializer;

/**
 * ReturnsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createReturn
     *
     * Create return.
     *
     */
    public function testCreateReturn()
    {
    }

    /**
     * Test case for getReturn
     *
     * Get a return by return id.
     *
     */
    public function testGetReturn()
    {
    }

    /**
     * Test case for getReturns
     *
     * Get returns.
     *
     */
    public function testGetReturns()
    {
    }

    /**
     * Test case for handleReturn
     *
     * Handle a return.
     *
     */
    public function testHandleReturn()
    {
    }
}
