<?php
/**
 * ShippingLabelsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\BolClient;

use \Swagger\BolClient\Configuration;
use \Swagger\BolClient\ApiException;
use \Swagger\BolClient\ObjectSerializer;

/**
 * ShippingLabelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShippingLabelsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getDeliveryOptions
     *
     * Get delivery options for a shippable configuration of a number of order items within an order..
     *
     */
    public function testGetDeliveryOptions()
    {
    }

    /**
     * Test case for getShippingLabel
     *
     * Get a shipping label.
     *
     */
    public function testGetShippingLabel()
    {
    }

    /**
     * Test case for postShippingLabel
     *
     * Create a shipping label.
     *
     */
    public function testPostShippingLabel()
    {
    }
}
