<?php
/**
 * SubscriptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\BolClient;

use \Swagger\BolClient\Configuration;
use \Swagger\BolClient\ApiException;
use \Swagger\BolClient\ObjectSerializer;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\BolClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePushNotificationSubscription
     *
     * BETA: Delete push notification subscription.
     *
     */
    public function testDeletePushNotificationSubscription()
    {
    }

    /**
     * Test case for getPushNotificationSubscription
     *
     * BETA: Get push notification subscription by id.
     *
     */
    public function testGetPushNotificationSubscription()
    {
    }

    /**
     * Test case for getPushNotificationSubscriptions
     *
     * BETA: Get push notification subscriptions.
     *
     */
    public function testGetPushNotificationSubscriptions()
    {
    }

    /**
     * Test case for postPushNotificationSubscription
     *
     * BETA: Create push notification subscription.
     *
     */
    public function testPostPushNotificationSubscription()
    {
    }

    /**
     * Test case for postTestPushNotification
     *
     * BETA: Send test push notification for subscriptions.
     *
     */
    public function testPostTestPushNotification()
    {
    }

    /**
     * Test case for putPushNotificationSubscription
     *
     * BETA: Update push notification subscription.
     *
     */
    public function testPutPushNotificationSubscription()
    {
    }
}
